### ISSUE TITLE
Implement std::ops::SliceIndex for `BoundedRange<usize>` (etc)

### ISSUE THREAD

**Issue by jsgf** [rsnively/rangetools#8]
It would be very useful to be able to use the various bounded range types as slice indexes.

Also, it doesn't seem possible to extract or view the `T` from `LowerBound<T>`/`UpperBound<T>` which would allow this to be implemented manually? Or convert a BoundedRange into plain std::ops::Range types? Or am I missing some piece of the API?

**Comment by rsnively** [comment]
Implementing SliceIndex seems like an obvious improvement. Thanks for the suggestion.

I see what you mean about extracting the inner T. I was hoping to avoid footguns with exclusive values because they have different meanings in the contexts of lower and upper bounds (thus the private inner bound). But I could see giving the range types `lower_bound() -> Bound<T>` functions where applicable with stern warnings to be responsible about their usage. Don't want to restrict usage just because of my paranoia.

Being able to convert the crate range types back into the standardized ones is interesting too (and maybe even having some TryFrom implementations for the set types). Things might get weird with exclusive lower bounds which the standards don't support, but I could see there being reasonable representations for those.

Thank you for the critical eye!

**Comment by rsnively** [comment]
version 0.1.4 addresses these issues!

Unfortunatley `std::slice::SliceIndex` is a sealed trait, so we had to make do with `std::ops::Index` and `std::ops::IndexMut`. I implemented those traits for all of the types that the `std::ops` ranges implement them for without digging into it too much deeper. (For example, `std::ffi::OsString` only has an `Index<RangeFull>` implementation, so I only provided an `Index<UnboundedRange>` implementation for that particular type).

There are now `.to_bound() -> Bound<T>` functions for both `LowerBound` and `UpperBound`.

And there are also `From` implementations for converting all of the crate range types into the applicable `std::ops` range types.
